ekf_filter_node:
  ros__parameters:
    two_d_mode: true
    publish_tf: true

    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # SLAM
    # pose0: /pose
    # pose0_config: [true, true, false,
    #                false, false, true,
    #                false, false, false,
    #                false, false, false,
    #                false, false, false]
    # pose0_differential: false
    # pose0_relative: false

    # IMU
    imu0: "imu/data_livox"
    imu0_config: [false, false, false, # Pose
                  true, true, true,    # Orient
                  false, false, false, # Lin Vel
                  true, true, true,    # Ang Vel
                  false, false, false]    # Lin Accel
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    # Wheel encoder velocity
    # odom0: "odom"
    # odom0_config: [true, true, false, # Pose
    #                 false, false, false, # Orient
    #                 true, false, false,  # Lin Vel
    #                 false, false, true,  # Ang Vel
    #                 false, false, false] # Lin Accel